name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - uses: actions/cache@v2
        with:
          path: result/bin/haskell-org-site
          key: ${{ runner.os }}-${{ hashFiles('*.cabal', '**/*.nix', '**/*.hs') }}
          restore-keys: ${{ runner.os }}-

      - name: Build Executable
        run: if [ ! -f result/bin/haskell-org-site ]; then nix-build; fi

      - name: Build Site
        run:  file result/bin/haskell-org-site && result/bin/haskell-org-site build

      - name: Check Links
        run: nix-shell --command 'linkchecker _site'
